language: java
jdk: oraclejdk8
addons:
 apt:
  packages:
   - oracle-java8-installer
# add this if you use maven for your project and want to verify mvn build is successful and all unit tests pass.
script:
 - mvn clean install
